freebsd_instance:
  image: freebsd-12-2-release-amd64
  # cpu: 1 gives an error; >2 works
  cpu: 2
  memory: 8G

env:
  CIRRUS_CLONE_DEPTH: 1
  # GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]

task:
  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  only_if: $CIRRUS_TAG !=~ 'continuous.*'

  env:
    matrix:
      DESKTOP: 'mate'

  env:
    matrix:
      arch: 'amd64'

  install_script:
    - ls -lh /usr/src || true
    - env
    - kldload zfs.ko
    - kldload tmpfs.ko
    - kldload nullfs.ko
    - kldload geom_uzip.ko
    - pkg install -y pkg git-lite zsync wget sha bash # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd
    - mount -t tmpfs tmpfs /usr/local/furybsd
    
  test_script:
    - /bin/sh -x ./build.sh "${DESKTOP}" || true # FIXME: Why does this return an error even though the ISO succeeded?
    - df -h
    - ( cd "${CIRRUS_WORKING_DIR}"/artifacts ; zsyncmake *.iso )
    - ls -lh "${CIRRUS_WORKING_DIR}"/artifacts/
    # wget -c "https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh"
    # export TRAVIS_REPO_SLUG="${CIRRUS_REPO_FULL_NAME}"
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous-"${DESKTOP}" "${CIRRUS_WORKING_DIR}"/artifacts ; esac
